services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    depends_on:
      - citypulse-web
      - citypulse-service
      - citypulse-database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
      - ./traefik/certs:/certs
      - ./traefik/dynamic:/etc/traefik/dynamic
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--providers.file.watch=true'
      - '--api.insecure=true'
      - '--api.dashboard=true' # Enabled for both, but not insecurely for prod by default
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker.defaultrule=Host(`{{ normalize .Name }}.citypulse.localhost`)'
    networks:
      - shared-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)'
      - 'traefik.http.routers.traefik-dashboard.service=api@internal'
      - 'traefik.http.routers.traefik-dashboard.entrypoints=websecure'
      - 'traefik.http.routers.traefik-dashboard.tls=true'

  citypulse-web:
    restart: on-failure
    build: ./nodes/citypulse-web
    hostname: citypulse-web
    environment:
      - NODE_ENV=development
      - ALLOWED_ORIGINS=
      - VITE_PUBLIC_NODE_ENV=development
      - VITE_PUBLIC_DOMAIN=.citypulse.localhost
      - VITE_PUBLIC_CITYPULSE_SERVICE_ENDPOINT=https://citypulse-service.citypulse.localhost
      - VITE_PUBLIC_API_ENDPOINT=https://citypulse-service.citypulse.localhost
      - VITE_PUBLIC_AUTH_API_ENDPOINT=https://citypulse-service.citypulse.localhost
    networks:
      - shared-network
    volumes: # Mount code and node_modules only in dev
      - ./nodes/citypulse-web:/app
      - citypulse-web-node_modules:/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.citypulse-web.entrypoints=websecure'
      - 'traefik.http.routers.citypulse-web.rule=Host(`citypulse-web.citypulse.localhost`)'
      - 'traefik.http.routers.citypulse-web.tls=true'
      - 'traefik.http.services.citypulse-web.loadbalancer.server.port=5173'

  citypulse-service:
    restart: on-failure
    build: ./nodes/citypulse-service
    hostname: citypulse-service
    environment:
      - NODE_ENV=development
      - ALLOWED_ORIGINS=https://citypulse-web.citypulse.localhost
      - DOMAIN=.citypulse.localhost
      - CITYPULSE_DATABASE_ENDPOINT=https://citypulse-database.citypulse.localhost
      - POSTGRES_CITYPULSE_DATABASE_DATABASE_URL=postgres://postgres:db_pass@citypulse-database:5432/postgres
      - POSTGRES_DATABASE_URL=postgres://postgres:db_pass@citypulse-database:5432/postgres
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=https://citypulse-service.citypulse.localhost/github/callback
    networks:
      - shared-network
    volumes: # Mount code and node_modules only in dev
      - ./nodes/citypulse-service:/app
      - citypulse-service-node_modules:/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.citypulse-service.entrypoints=websecure'
      - 'traefik.http.routers.citypulse-service.rule=Host(`citypulse-service.citypulse.localhost`)'
      - 'traefik.http.routers.citypulse-service.tls=true'
      - 'traefik.http.services.citypulse-service.loadbalancer.server.port=3000'

  citypulse-database:
    restart: on-failure
    build: ./nodes/citypulse-database
    hostname: citypulse-database
    environment:
      - NODE_ENV=development
      - ALLOWED_ORIGINS=https://citypulse-service.citypulse.localhost
      - POSTGRES_PASSWORD=db_pass
      - port=5432
    networks:
      - shared-network
    ports: # Expose DB port only in dev if specified
      - '5432:5432'
    volumes:
      - citypulse-database-data:/var/lib/postgresql/data

networks:
  shared-network:
    driver: bridge


volumes:
  citypulse-web-node_modules:
  citypulse-service-node_modules:
  citypulse-database-data: # Development data volume for DB

